#undefine EPSINF
#undefine GLM
#undefine NORMINIT
#undefine EXTRAFLAGS
#define ENTROPY
#undefine ELECTRONS
#define STAGGERED
#undefine SFC_ON_BASE
#undefine HALL
#undefine UCONVERT
#undefine SAVENOW
#undefine TRANSFORMW
#undefine RAY
#undefine BIGENDIAN
#undefine FOURTHORDER
#undefine TCRKL2
#undefine TCPERPENDICULAR
#undefine SPECIALTOLERANCE
#undefine MAGNETOFRICTION
#undefine PARTICLES
#undefine BOUNDARYDRIVER
